services:

  migra:
    build:
      dockerfile: ./migra.Containerfile
    command: sleep infinity

  db-a:
    build:
      dockerfile: ./a.Containerfile
    container_name: db-a
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    ports:
      - "9876:5432"

  db-b:
    build:
      dockerfile: ./b.Containerfile
    container_name: db-b
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    ports:
      - "8765:5432"

