services:

  postgres_migrator:
    build:
      dockerfile: ./postgres_migrator.Containerfile
    environment:
      PG_URL: postgresql://glvd:glvd@db-a:5432/glvd?sslmode=disable
    command: sleep infinity

  db-a:
    build:
      dockerfile: ./a.Containerfile
    container_name: db-a
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    ports:
      - "9876:5432"

