name: Dump GLVD Postgres Snapshot
on:
  workflow_dispatch:

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: ghcr.io/gardenlinux/glvd:edge

    services:
      postgres:
        image: ghcr.io/gardenlinux/glvd-postgres:edge
        env:
          POSTGRES_USER: glvd
          POSTGRES_DB: glvd
          POSTGRES_PASSWORD: glvd
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: prepare
        run: |
          apt-get update
          apt-get -yqq install curl debian-archive-keyring postgresql-client
          mkdir -p data/ingest-debsec/{debian,gardenlinux}/CVE
          mkdir -p data/ingest-debsec/debian/CVE
          mkdir -p data/ingest-debsrc/debian
          mkdir -p data/ingest-debsrc/var/lib/dpkg
          touch data/ingest-debsrc/var/lib/dpkg/status
          curl https://salsa.debian.org/security-tracker-team/security-tracker/-/raw/master/data/CVE/list?ref_type=heads \
              --output data/ingest-debsec/debian/CVE/list
          APT_CONFIG=conf/ingest-debsrc/apt.conf apt update \
            -o Dir="$PWD/data/ingest-debsrc/" \
            -o Dir::Etc::sourcelist="$PWD/conf/ingest-debsrc/debian.sources" \
            -o Dir::State="$PWD/data/ingest-debsrc/"

      - name: Run data ingestion (nvd)
        run: glvd-data ingest-nvd
        env:
          PGUSER: glvd
          PGDATABASE: glvd
          PGPASSWORD: glvd
          PGHOST: postgres
          PGPORT: 5432

      - name: Run data ingestion (ingest-debsec - debian)
        run: glvd-data ingest-debsec debian data/ingest-debsec/debian
        env:
          PGUSER: glvd
          PGDATABASE: glvd
          PGPASSWORD: glvd
          PGHOST: postgres
          PGPORT: 5432

      - name: Run data ingestion (ingest-debsec - gardenlinux)
        run: glvd-data ingest-debsec gardenlinux data/ingest-debsec/gardenlinux
        env:
          PGUSER: glvd
          PGDATABASE: glvd
          PGPASSWORD: glvd
          PGHOST: postgres
          PGPORT: 5432

      - name: Run data combination (combine-deb)
        run: glvd-data combine-deb
        env:
          PGUSER: glvd
          PGDATABASE: glvd
          PGPASSWORD: glvd
          PGHOST: postgres
          PGPORT: 5432

      - name: Run data combination (combine-all)
        run: glvd-data combine-all
        env:
          PGUSER: glvd
          PGDATABASE: glvd
          PGPASSWORD: glvd
          PGHOST: postgres
          PGPORT: 5432

      - name: Dump Database Snapshot
        run: |
          echo "postgres:5432:glvd:glvd:glvd" >  ~/.pgpass
          chmod 0600 ~/.pgpass
          pg_dump -h postgres -p 5432 -U glvd glvd > glvd.sql

      - uses: actions/upload-artifact@v4
        with:
          name: glvd.sql
          path: glvd.sql
          retention-days: 2
